name: tui

on:
  push:
    paths:
      - "tui/**"
      - ".github/workflows/tui.yml"
  pull_request:
    paths:
      - "tui/**"

jobs:
  go-tui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: tui/go.mod
      - name: Test TUI
        run: |
          cd tui
          go test ./...
